service: www-dashboard-api
runtime: custom
env: flex

# For manual deployment, replace the variables starting with $ with your own values
env_variables:
  # Required
  STAGE: $STAGE
  ALLOW_ORIGINS: $ALLOW_ORIGINS

  # Optional
  ACCESS_TOKEN_SECRET_KEY: $ACCESS_TOKEN_SECRET_KEY
  NEW_RELIC_URL: $NEW_RELIC_URL
  NEWRELIC_API_KEY: $NEWRELIC_API_KEY
  TRANSLATIONS_ENABLED: $TRANSLATIONS_ENABLED
  CLOUD_SERVICE: google
  GOOGLE_MAPS_API_KEY: $GOOGLE_MAPS_API_KEY
  ADMIN_PASSWORD: $ADMIN_PASSWORD
  OWNER_NAME: $OWNER_NAME
  OWNER_URL: $OWNER_URL
  COMPANY_NAME: $COMPANY_NAME
  COMPANY_URL: $COMPANY_URL
  GOOGLE_CREDENTIALS_JSON_B64: $GOOGLE_CREDENTIALS_JSON_B64
  GOOGLE_CLOUD_STORAGE_BUCKET_FILE: $GOOGLE_CLOUD_STORAGE_BUCKET_FILE
  GOOGLE_CLOUD_STORAGE_BUCKET_TMP_DATA: $GOOGLE_CLOUD_STORAGE_BUCKET_TMP_DATA
  
  WRA03A_PASSWORD: $WRA03A_PASSWORD
  WWWPAKISTAN_PASSWORD: $WWWPAKISTAN_PASSWORD
  PMN01A_PASSWORD: $PMN01A_PASSWORD
  MIDWIFE_PASSWORD: $MIDWIFE_PASSWORD
  HEALTHWELLBEING_PASSWORD: $HEALTHWELLBEING_PASSWORD
  GIZ_PASSWORD: $GIZ_PASSWORD

manual_scaling:
  instances: 1

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 10

# Force https and redirect http to https
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

