name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: wwwapi

jobs:

  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0.4.1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        service_account: 'deft-stratum-290216@appspot.gserviceaccount.com'
    - uses: google-github-actions/auth@v1
      with:
        project_id: deft-stratum-290216
        export_default_credentials: true

#    - name: Log into registry
#      uses: docker/login-action@v1
#      with:
#          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
#          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
#          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: gcr.io/deft-stratum-290216/wwwapi:${{ github.sha }}

#
#  deploy:
#    runs-on: ubuntu-latest
#
#    needs: build
#
#    environment:
#      name: 'production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#      - name: Lowercase the repo name
#        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
#
#      - name: Deploy to Azure Web App
#        id: deploy-to-webapp
#        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
#        with:
#          app-name: wellcomeharmonyapi
#          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#          images: regprotocolsfds.azurecr.io/harmonyapi:${{ github.sha }}
