name: "Open Source: Google App Engine, Build and deploy dashboard API"


on:
  push:
    branches: [ "open-source" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "open-source" ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  IMAGE_NAME: wwwdashboardapi-open-source
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:

  build:
    name: Build container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Include credentials
        run: |
          touch credentials.json
          echo ${{ env.GOOGLE_CREDENTIALS }} > credentials.json

      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          service_account: 'deft-stratum-290216@appspot.gserviceaccount.com'
          project_id: deft-stratum-290216
          export_default_credentials: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Configure Docker'
        run: 'gcloud auth configure-docker'

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: gcr.io/deft-stratum-290216/wwwdashboardapi-open-source:${{ github.sha }}

      - name: Deploy
        run: gcloud app deploy app-open-source.yaml --image-url=gcr.io/deft-stratum-290216/wwwdashboardapi-open-source:${{ github.sha }}
